
// global.coreController = use('core.controllers.controller')
// global.coreModel = use('core.database.model')
// global.coreEntity = use('core.database.entity')
// global.coreRepository = use('core.database.repository')
// global.coreCommand = use('core.commands.command')
// global.coreService = use('core.services.service')
// global.coreMiddleware = use('core.middlewares.middleware')
// global.coreValidtor = use('core.http.validtor')
global.ScheduleRunner = use('core.timer.ScheduleRunner')